server:
  port: 8094
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics
info:
  app:
    name: location
    version: @version@
    buildtime: @timestamp@

spring:
  datasource:
    location:
      url: jdbc:postgresql://localhost:5443/location?currentSchema=location
      username: user
      password: pwd
      driver-class-name: org.postgresql.Driver
    service-point:
      url: jdbc:postgresql://localhost:5439/service-point-directory?currentSchema=service_point_directory
      username: user
      password: pwd
      driver-class-name: org.postgresql.Driver
    prm:
      url: jdbc:postgresql://localhost:5442/prm-directory?currentSchema=prm_directory
      username: user
      password: pwd
      driver-class-name: org.postgresql.Driver
  application:
    name: location
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/2cda5d11-f0ac-46b3-967d-af1b2e1bd01a/v2.0
        registration:
          azure:
            authorization-grant-type: client_credentials
            client-id: test # todo: why do i have to configure this, it works also with test
            client-secret: test
            scope:
              - api://87e6e634-6ba1-4e7a-869d-3348b4c3eafc/.default
auth:
  audience:
    service-name: 87e6e634-6ba1-4e7a-869d-3348b4c3eafc
